<?php
/**
 * Typography.
 *
 * @package Calens
 */
return array(
	'title'            => esc_html__( 'Typography', 'calens' ),
	'id'               => 'typography_settings',
	'customizer_width' => '400px',
	'icon'             => 'el el-fontsize',
	'fields'           => array(
		array(
			'id'             => 'custom_heading_title_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Title Font', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for heading title.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Poppins', 
				'font-backup' => 'Barlow Condensed, Helvetica, sans-serif', 
				'font-weight' => '700', 
				'google'      => true,
				'font-size'   => '52', 
				'line-height' => '52',
			),
		),
		array(
			'id'             => 'custom_heading_subtitle_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Subtitle Font', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for heading subtitle.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family'    => 'Poppins',
				'font-weight'    => '600', 
				'google'         => true,
				'font-size'      => '15', 
				'line-height'    => '24',
			),
		),
		array(
			'id'             => 'body_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Body Font', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for body tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Poppins', 
				'font-backup' => 'Arial, Helvetica, sans-serif', 
				'font-weight' => '400', 
				'google'      => true,
				'font-size'   => '15', 
				'line-height' => '26',
			),
		),
		array(
			'id'             => 'h1_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H1 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h1 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family'    => 'Barlow Condensed', 
				'font-backup'    => 'Arial, Helvetica, sans-serif', 
				'font-weight'    => '700', 
				'google'         => true,
				'font-size'      => '46px', 
				'line-height'    => '50px',
				'letter-spacing' => '0px',
			),
		),
		array(
			'id'             => 'h2_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H2 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h2 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family'    => 'Barlow Condensed', 
				'font-weight'    => '700', 
				'google'         => true,
				'font-size'      => '40px', 
				'line-height'    => '46px',
				'letter-spacing' => '0px',
			),
		),
		array(
			'id'             => 'h3_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H3 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h3 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Barlow Condensed', 
				'font-weight' => '700', 
				'google'      => true,
				'font-size'   => '36px', 
				'line-height' => '42px',
			),
		),
		array(
			'id'             => 'h4_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H4 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h4 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Barlow Condensed', 
				'font-weight' => '700', 
				'google'      => true,
				'font-size'   => '30px', 
				'line-height' => '36px',
			),
		),
		array(
			'id'             => 'h5_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H5 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h5 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Barlow Condensed', 
				'font-weight' => '700', 
				'google'      => true,
				'font-size'   => '26px', 
				'line-height' => '30px',
			),
		),
		array(
			'id'             => 'h6_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H6 Headers Typography', 'calens' ),
			'subtitle'       => esc_html__( 'Specify typography for h6 tag.', 'calens' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => true,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
			'default'        => array(
				'font-family' => 'Barlow Condensed', 
				'font-weight' => '700', 
				'google'      => true,
				'font-size'   => '22px', 
				'line-height' => '26px',
			),
		),
	),
);
